Moved env identification towards labels

diff --git a/.github/workflows/prepare-and-deploy-env.yaml b/.github/workflows/prepare-and-deploy-env.yaml
--- a/.github/workflows/prepare-and-deploy-env.yaml
+++ b/.github/workflows/prepare-and-deploy-env.yaml
@@ -53,7 +53,7 @@ on:
       bunnyshell-cli-version:
         description: The version of the Bunnyshell CLI to use
         type: string
-        default: v0.16.0
+        default: v0.18.0
     secrets:
       bunnyshell-access-token:
         required: true
@@ -144,18 +144,20 @@ jobs:
           echo "BNS_GIT_SHA=`git rev-parse --short HEAD`" >> "$GITHUB_ENV"
       - name: Search for Environment
         uses: addnab/docker-run-action@v3
-        if: ${{ inputs.env-name != '' }}
+        if: ${{ inputs.pr-number != '' }}
         with:
           image: bunnyshell/cli:${{ inputs.bunnyshell-cli-version }}
           options: -e BUNNYSHELL_TOKEN=${{ secrets.bunnyshell-access-token }} -v ${{ github.env }}:/github/envs.txt
           run: |
             set -e
   
-            BNS_ENV_ID=`bns environments list --search "${{ inputs.env-name }}" --project ${{ inputs.project-id }} --non-interactive -o json \
+            BNS_ENV_ID=`bns environments list --label "auto-gha=pr-${{ inputs.pr-number }}" --project ${{ inputs.project-id }} --non-interactive -o json \
               | jq -r "try ._embedded.item[0].id | select (.!=null)"`
   
             if [ -z "$BNS_ENV_ID" ]; then
-              echo "Could not find environment with name '${{ inputs.env-name }}'."
+              echo "Could not find environment with label 'auto-gha=pr-${{ inputs.pr-number }}'."
+            
+              exit 1
             fi
   
             echo "BNS_ENV_ID=$BNS_ENV_ID" >> /github/envs.txt
@@ -201,6 +203,7 @@ jobs:
             echo "BNS_ENV_CREATED=1" >> /github/envs.txt
   
             CREATE_ENV_OUTPUT=`bns environments create --name "${{ inputs.env-name }}" --from-path /work/bunnyshell_wf_updated.yaml \
+              --label "auto-gha=pr-${{ inputs.pr-number }}" \
               --k8s "${{ inputs.cluster-id }}" --project ${{ inputs.project-id }} --non-interactive -o json`
             if [ "$?" != "0" ]; then
               echo "Failed to create the environment: $CREATE_ENV_OUTPUT"
